/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ciafactfinder;
import java.util.Scanner;
import java.io.IOException;
import java.io.FileInputStream;
import java.util.Arrays;
/**
 *
 * @author manav
 */
public class Finder extends javax.swing.JFrame {
    String[] countries;
    String[] birthRate;
    String[] population;
    String[] GDP;
    String[] unemplo;
    int countr = 0;
    /**
     * Creates new form Finder
     */
    public Finder() {
        
        countries = new String[25];
        birthRate = new String[25];
        population = new String[25];
        GDP = new String[25];
        unemplo = new String[25];
        
        initComponents();
        loadItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        gdp = new javax.swing.JLabel();
        unemp = new javax.swing.JLabel();
        pop = new javax.swing.JLabel();
        birRate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(565, 332));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Egypt", "Singapore", "Spain", "Pakistan", "Netherlands", "Qatar", "Sweden", "Italy", "Switzerland", "Australia", "India", "Turkey", "Iran", "Canada", "SouthKorea", "UAE", "SaudiArabia", "Israel", "Japan", "France", "UK", "Germany", "China", "Russia", "USA" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        gdp.setForeground(new java.awt.Color(255, 255, 255));
        gdp.setText("0");
        getContentPane().add(gdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        unemp.setForeground(new java.awt.Color(255, 255, 255));
        unemp.setText("0");
        getContentPane().add(unemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        pop.setForeground(new java.awt.Color(255, 255, 255));
        pop.setText("0");
        getContentPane().add(pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        birRate.setForeground(new java.awt.Color(255, 255, 255));
        birRate.setText("0");
        getContentPane().add(birRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GDP:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Unemployment:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Population:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Birth rate:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Find Out About a Country:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/manav/Downloads/Untitled drawing.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/manav/Downloads/FactFInder/Preview Image.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String search = (jComboBox1.getSelectedItem()).toString();
        for(int i = 0;i < countries.length;i++){
            if(countries[i].equals(search)){
                gdp.setText(GDP[i]);
                pop.setText(population[i]);
                birRate.setText(birthRate[i]);
                unemp.setText(unemplo[i]);
                pop.setText(population[i]);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void loadItems() //Precondtions: N/A | Post: The values in the txt file will be inputted into 2 arrays, storeItem and itemPrice
    {
        try {
            String filename = "src/main/java/com/mycompany/ciafactfinder/Countries.txt";
            Scanner infile = new Scanner(new FileInputStream(filename));

            while (countr < 25) {
                
                countries[countr] = infile.next();
                birthRate[countr] = infile.next();
                population[countr] = infile.next();
                unemplo[countr] = infile.next();
                GDP[countr] = infile.next();
                countr +=1;
            }
            System.out.println("countries: " + Arrays.toString(countries));
            infile.close();

        } catch (IOException ex) {
            countr = -1;
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Scanner myScanner = new Scanner(System.in);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birRate;
    private javax.swing.JLabel gdp;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel pop;
    private javax.swing.JLabel unemp;
    // End of variables declaration//GEN-END:variables
}
